#ifndef NS_AMS8051HEX_DIS_FUNC_H
#define NS_AMS8051HEX_DIS_FUNC_H
#include <map>
namespace NS_AMS8051HEX{

class to_asm;
typedef enum E_TYPE_DIS_OPR{
TOKEN_AB,
TOKEN_ACC,
TOKEN_ADDR11,
TOKEN_ADDR16,
TOKEN_AT_A_PLUS_DPTR,
TOKEN_AT_A_PLUS_PC,
TOKEN_AT_DPTR,
TOKEN_AT_RI,
TOKEN_BIT,
TOKEN_C,
TOKEN_DIRECT,
TOKEN_DPTR,
TOKEN_IMM16,
TOKEN_IMM8,
TOKEN_NBIT,
TOKEN_REL,
TOKEN_RN,
} E_TYPE_DIS_OPR;
typedef int (* DIS_FUNC_PTR) ( to_asm *dis, const std::string &mbin, int ibyte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_0FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_10H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_11H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_12H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_13H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_14H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_15H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_16H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_17H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_18H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_19H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_1FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_20H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_21H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_22H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_23H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_24H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_25H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_26H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_27H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_28H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_29H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_2FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_30H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_31H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_32H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_33H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_34H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_35H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_36H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_37H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_38H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_39H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_3FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_40H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_41H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_42H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_43H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_44H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_45H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_46H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_47H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_48H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_49H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_4FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_50H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_51H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_52H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_53H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_54H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_55H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_56H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_57H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_58H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_59H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_5FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_60H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_61H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_62H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_63H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_64H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_65H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_66H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_67H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_68H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_69H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_6FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_70H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_71H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_72H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_73H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_74H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_75H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_76H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_77H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_78H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_79H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_7FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_80H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_81H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_82H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_83H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_84H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_85H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_86H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_87H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_88H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_89H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_8FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_90H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_91H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_92H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_93H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_94H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_95H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_96H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_97H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_98H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_99H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9AH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9BH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9CH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9DH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9EH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_9FH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_A9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_AAH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_ABH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_ACH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_ADH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_AEH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_AFH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_B9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_BAH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_BBH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_BCH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_BDH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_BEH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_BFH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_C9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_CAH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_CBH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_CCH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_CDH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_CEH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_CFH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_D9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_DAH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_DBH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_DCH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_DDH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_DEH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_DFH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_E9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_EAH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_EBH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_ECH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_EDH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_EEH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_EFH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F0H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F1H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F2H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F3H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F4H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F5H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F6H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F7H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F8H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_F9H(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_FAH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_FBH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_FCH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_FDH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_FEH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int AA_FFH(to_asm* dis, const std::string &mbin, int i_byte_offset, unsigned curr_addr, std::ostream &mout);
int load_dis_funcs(std::map<unsigned, DIS_FUNC_PTR> &keys);
int get_inst_byte_len(unsigned first_byte);
}//namespace end
#endif
