name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make clean
      run: make clean
    - name: apt-get install flex bison
      run: sudo apt-get install -y flex bison
    - name: make
      run: make all
    - name: make test
      run: make test

